/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIFrames;


import UIFrames.*;
import Classes.DBConnection;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author CompuWorld
 */
public class editUser extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    //This object from DBConnection to make a connection to the database and close it.
    public static DBConnection dbc = new DBConnection();
    //This variable store the sql statement.
    public static PreparedStatement pst = null;
    //This variable store the result of any sql statement from the database.
    public static ResultSet rs = null;

    public static Integer userId = null;

    private void goBackToUsers() {
        Users u = new Users();
        editUser.this.dispose();
        u.setVisible(true);
    }

    public editUser() {
        dbc.ConnectDB();
        initComponents();
        WindowListener exitListener = null;
        addWindowListener(prepareWindow(exitListener));
    }

    private WindowListener prepareWindow(WindowListener exitListener) {
        exitListener = new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                Users u = new Users();
                editUser.this.dispose();
                u.setVisible(true);
            }
        };
        return exitListener;
    }

    private void clearErrorMsg() {
        nameErrorLabel.setText("");
        userNameErrorLabel.setText("");
        passwordErrorLabel.setText("");
        conPasswordErrorLabel.setText("");
        phoneErrorLabel.setText("");
    }

    private boolean validateR() {
        boolean check = true;
        if (ReNameTF.getText().length() > 200) {
            nameErrorLabel.setText("only 200 character");
            check = false;
        }
        if (ReUserNameTF.getText().length() > 45) {
            userNameErrorLabel.setText("only 45 character");
            check = false;
        }
        if (new String(RePassTF.getPassword()).length() > 45) {
            passwordErrorLabel.setText("only 45 character");
            check = false;
        }
        if (!new String(ReConfPassTF.getPassword()).equals(RePassTF.getText())) {
            conPasswordErrorLabel.setText("not the same");
            check = false;
        }
        if (RePhoneTF.getText().length() > 20) {
            phoneErrorLabel.setText("only 20 number");
            check = false;
        }
        return check;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ReJobTF = new javax.swing.JTextField();
        RePhoneTF = new javax.swing.JTextField();
        editUserBtn = new javax.swing.JButton();
        ReBackBtn = new javax.swing.JButton();
        ReNameTF = new javax.swing.JTextField();
        ReUserNameTF = new javax.swing.JTextField();
        nameErrorLabel = new javax.swing.JLabel();
        userNameErrorLabel = new javax.swing.JLabel();
        passwordErrorLabel = new javax.swing.JLabel();
        conPasswordErrorLabel = new javax.swing.JLabel();
        phoneErrorLabel = new javax.swing.JLabel();
        RePassTF = new javax.swing.JPasswordField();
        ReConfPassTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(417, 384));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name: ");
        jLabel1.setPreferredSize(new java.awt.Dimension(39, 14));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 26, -1, -1));

        jLabel2.setText("User Name: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 67, -1, -1));

        jLabel3.setText("Password: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 111, -1, -1));

        jLabel4.setText("Confirm Password: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 158, -1, -1));

        jLabel5.setText("Job Tittle: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 205, -1, -1));

        jLabel6.setText("Phone Number: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 254, -1, -1));

        ReJobTF.setEditable(false);
        ReJobTF.setText("Employee");
        ReJobTF.setEnabled(false);
        jPanel1.add(ReJobTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 201, 137, -1));

        RePhoneTF.setToolTipText("");
        RePhoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RePhoneTFActionPerformed(evt);
            }
        });
        jPanel1.add(RePhoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 250, 137, -1));

        editUserBtn.setText("Edit User");
        editUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 304, -1, -1));

        ReBackBtn.setText("Back");
        ReBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReBackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ReBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 338, -1, -1));

        ReNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(ReNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 21, 137, -1));

        ReUserNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReUserNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(ReUserNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 63, 137, -1));

        nameErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        nameErrorLabel.setPreferredSize(new java.awt.Dimension(110, 14));
        jPanel1.add(nameErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 26, -1, -1));

        userNameErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        userNameErrorLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        jPanel1.add(userNameErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 67, -1, -1));

        passwordErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        passwordErrorLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        jPanel1.add(passwordErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 111, -1, -1));

        conPasswordErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        conPasswordErrorLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        jPanel1.add(conPasswordErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 158, -1, -1));

        phoneErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        phoneErrorLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        jPanel1.add(phoneErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 254, -1, -1));
        jPanel1.add(RePassTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, -1));
        jPanel1.add(ReConfPassTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 417, 384);

        setSize(new java.awt.Dimension(433, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserBtnActionPerformed
        if (!ReNameTF.getText().equals("") && !ReUserNameTF.getText().equals("")
                && !RePassTF.getText().equals("") && !ReConfPassTF.getText().equals("") && !ReJobTF.equals("")) {
            try {
                if (!validateR()) {
                    JOptionPane.showMessageDialog(this, "Please check your wrong data", "Error", 0);
                    return;
                }
                clearErrorMsg();
                pst = dbc.conn.prepareStatement("update User_Information set user_name=?, name=?, password=?,"
                        + "jobtitle=?, phone=? where id=" + userId);
                pst.setString(2, ReNameTF.getText());
                pst.setString(1, ReUserNameTF.getText());
                pst.setString(3, RePassTF.getText());
                pst.setString(4, "emp");
                pst.setString(5, RePhoneTF.getText());
                int Flag = pst.executeUpdate();
                if (Flag == 0) {
                    JOptionPane.showMessageDialog(null, "Editing data has failed\nplease try again\nor contact Codotronic", "Error", 0);

                } else {
                    JOptionPane.showMessageDialog(null, "Editing data has been successful", "Successful", 1);
                    goBackToUsers();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "User name already exist\nplease try another one", "Warning", 2);
                nameErrorLabel.setText("already exist");
            }
        } else {
            JOptionPane.showMessageDialog(this, "please fill the empty fields first\n(you may not enter a phone number)", "Warning", 2);
        }
    }//GEN-LAST:event_editUserBtnActionPerformed

    private void ReBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReBackBtnActionPerformed
        goBackToUsers();
    }//GEN-LAST:event_ReBackBtnActionPerformed

    private void ReNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReNameTFActionPerformed
        editUserBtn.doClick();
    }//GEN-LAST:event_ReNameTFActionPerformed

    private void ReUserNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReUserNameTFActionPerformed
        editUserBtn.doClick();
    }//GEN-LAST:event_ReUserNameTFActionPerformed

    private void RePhoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RePhoneTFActionPerformed
        editUserBtn.doClick();
    }//GEN-LAST:event_RePhoneTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReBackBtn;
    public static javax.swing.JPasswordField ReConfPassTF;
    public static javax.swing.JTextField ReJobTF;
    public static javax.swing.JTextField ReNameTF;
    public static javax.swing.JPasswordField RePassTF;
    public static javax.swing.JTextField RePhoneTF;
    public static javax.swing.JTextField ReUserNameTF;
    private javax.swing.JLabel conPasswordErrorLabel;
    private javax.swing.JButton editUserBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameErrorLabel;
    private javax.swing.JLabel passwordErrorLabel;
    private javax.swing.JLabel phoneErrorLabel;
    private javax.swing.JLabel userNameErrorLabel;
    // End of variables declaration//GEN-END:variables
  
}
