/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIFrames;

import UIPanels.Old_Bills;
import UIPanels.Sell_Bill_Panel;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author CompuWorld
 */
public class Sell_Bill extends javax.swing.JFrame {

    /**
     * Creates new form Sell_Bill
     */
    public Sell_Bill() {
        initComponents();
        
        if (!Login.dbc.check) {
            Login.dbc.ConnectDB();
        }

        try {
            Login.pst = Login.dbc.conn.prepareStatement("select Bill_Num from Sales where Bill_Num=(select max(Bill_Num) from Sales)");
            Login.rs = Login.pst.executeQuery();
            if(Login.rs.next())
            {
                BillNum=Login.rs.getInt("Bill_Num")+1;
            }
            else
            {
                BillNum=1;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        billTab.add("New Bill",new Sell_Bill_Panel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billTab = new javax.swing.JTabbedPane();
        OldBillBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        billTab.setPreferredSize(new java.awt.Dimension(970, 500));
        getContentPane().add(billTab);
        billTab.setBounds(10, 11, 1040, 460);

        OldBillBtn.setText("Open Old Bills");
        OldBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldBillBtnActionPerformed(evt);
            }
        });
        getContentPane().add(OldBillBtn);
        OldBillBtn.setBounds(430, 490, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int BillNum;
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void OldBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldBillBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,new Old_Bills());
    }//GEN-LAST:event_OldBillBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OldBillBtn;
    public static javax.swing.JTabbedPane billTab;
    // End of variables declaration//GEN-END:variables
  
}
