/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package UIPanels;

import UIFrames.Login;
import UIFrames.Sell_Bill;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Calendar;
import java.util.LinkedHashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CompuFast
 */
public class Sell_Bill_Panel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Sell_Bill_Panel() {
        initComponents();
        Table.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 13));
        Table.getTableHeader().setAlignmentY(CENTER_ALIGNMENT);
        Table.setAutoCreateColumnsFromModel(false);
        
        
        AddCodeTF.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                AddCodeBtn.setEnabled(true);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                AddCodeBtn.setEnabled(true);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                AddCodeBtn.setEnabled(true);
            }
        });
        Sell_Bill.billTab.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                getCurrentDataOnTab();
            }

            @Override
            public void focusLost(FocusEvent e) {
              
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CashNameTF = new javax.swing.JTextField();
        ShiftTF = new javax.swing.JTextField();
        DateTF = new javax.swing.JTextField();
        TimeTF = new javax.swing.JTextField();
        TotalTF = new javax.swing.JTextField();
        BillNumTF = new javax.swing.JTextField();
        PNumTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        AddCodeBtn = new javax.swing.JButton();
        AddCodeTF = new javax.swing.JTextField();
        PrintBtn = new javax.swing.JButton();
        NewOrderBtn = new javax.swing.JButton();

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category No.", "Category", "Product Name", "Barcode", "Product Unit", "Quantity", "Price", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        jLabel1.setText("Casher Name: ");

        jLabel2.setText("Shift: ");

        jLabel3.setText("Bill Number: ");

        jLabel4.setText("Date: ");

        jLabel5.setText("Time: ");

        jLabel6.setText("Pieces Number: ");

        jLabel7.setText("Total: ");

        CashNameTF.setEditable(false);

        ShiftTF.setEditable(false);

        DateTF.setEditable(false);

        TimeTF.setEditable(false);

        TotalTF.setEditable(false);
        TotalTF.setText("0");

        BillNumTF.setEditable(false);

        PNumTF.setEditable(false);
        PNumTF.setText("0");

        AddCodeBtn.setText("Add Code");
        AddCodeBtn.setEnabled(false);
        AddCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCodeBtnActionPerformed(evt);
            }
        });

        AddCodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCodeTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(AddCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PrintBtn.setText("Print");
        PrintBtn.setEnabled(false);
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });

        NewOrderBtn.setText("New Order");
        NewOrderBtn.setEnabled(false);
        NewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PNumTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(TimeTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShiftTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CashNameTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BillNumTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalTF))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewOrderBtn))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BillNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CashNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShiftTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(NewOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public LinkedHashMap<String, Double> pdtMap = new LinkedHashMap<>();
    
    double total_ammount=0;
    double total_price=0;
    
    private void clearData()
    {
        DefaultTableModel tm=(DefaultTableModel)Table.getModel();
        tm.setRowCount(0);
        BillNumTF.setText("");
        CashNameTF.setText("");
        ShiftTF.setText("");
        DateTF.setText("");
        TimeTF.setText("");
        PNumTF.setText("");
        TotalTF.setText("");
        AddCodeTF.setText("");
        AddCodeBtn.setEnabled(false);
        PrintBtn.setEnabled(false);
        NewOrderBtn.setEnabled(false);
    }
    
    private void getCurrentDataOnTab()
    {
        BillNumTF.setText(String.valueOf(Sell_Bill.BillNum));
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEE d-MMM-yyyy",Locale.ENGLISH);
        LocalDate localDate=LocalDate.now();
        DateTF.setText(localDate.format(formatter));

        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        TimeTF.setText(sdf.format(cal.getTime()));
    }
    
    
    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        try {
            
            for (int i = 0; i < Table.getRowCount(); i++) {
                Login.pst = Login.dbc.conn.prepareStatement("update Store set quantity=quantity-? where barcode = ?");
                Login.pst.setDouble(1, (double)Table.getValueAt(i, 5));
                Login.pst.setString(2, Table.getValueAt(i, 3).toString());
                Login.pst.executeUpdate();
                BillNumTF.setText(String.valueOf(Sell_Bill.BillNum));
                
                Login.pst = Login.dbc.conn.prepareStatement("insert into Sales (Bill_Num,Barcode,Category_Num,Category_Name,Product_Name,Product_Unit,Quantity_Sold,Price,Total_Price,Date,Time) values (?,?,?,?,?,?,?,?,?,?,?)");
                Login.pst.setInt(1, Integer.parseInt(BillNumTF.getText()));//Bill_Num
                Login.pst.setString(2, Table.getValueAt(i, 3).toString());//Barcode
                Login.pst.setInt(3, (int) Table.getValueAt(i, 0));//Category_Num
                Login.pst.setString(4, Table.getValueAt(i, 1).toString());//Category_Name
                Login.pst.setString(5, Table.getValueAt(i, 2).toString());//Product_Name
                Login.pst.setString(6, Table.getValueAt(i, 4).toString());//Product_Unit
                Login.pst.setDouble(7, (double) Table.getValueAt(i, 5));//Quantity_Sold
                Login.pst.setDouble(8, (double) Table.getValueAt(i, 6));//Price
                Login.pst.setDouble(9, (double) Table.getValueAt(i, 7));//Total_Price

                getCurrentDataOnTab();
                
                Login.pst.setString(10, DateTF.getText());//Date
                Login.pst.setString(11, TimeTF.getText());//Time
                
                Login.pst.execute();
            }
        JOptionPane.showMessageDialog(this, "The products are sold", "Info", 1);

        if(Sell_Bill.billTab.getTabCount()>1)
        {
            Sell_Bill.billTab.remove(Sell_Bill.billTab.getSelectedIndex());
        }

        else
        {
            clearData();
        }

        Sell_Bill.BillNum+=1;

        DefaultTableModel Model = (DefaultTableModel) Table.getModel();
        Model.setRowCount(0);
        PrintBtn.setEnabled(false);
        pdtMap.clear();
        total_ammount=0;
        total_price=0;
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "The products are not sold\nDatabase is not working\nplease contact Codotronic team", "Error", 0);
        }
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void AddCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCodeBtnActionPerformed

        try{
            DefaultTableModel tm=(DefaultTableModel)Table.getModel();
            Login.pst = Login.dbc.conn.prepareStatement("select * from Store where barcode = ? ");
            Login.pst.setString(1, AddCodeTF.getText());
            Login.rs = Login.pst.executeQuery();
            if (!Login.rs.next()) {
                JOptionPane.showMessageDialog(this, "this product is not found or stored", "Warning", 2);
                AddCodeTF.setText("");
                AddCodeBtn.setEnabled(false);
            } else {
                 if (!pdtMap.containsKey(AddCodeTF.getText())) {
                    pdtMap.put(AddCodeTF.getText(), 1.0);
                    tm.addRow(new Object[]{Login.rs.getInt("groupNumber"), Login.rs.getString("groupName"), Login.rs.getString("productName"), AddCodeTF.getText(), Login.rs.getString("unitOfMeasurment"), pdtMap.get(AddCodeTF.getText()), Login.rs.getDouble("sellingPrice"), Login.rs.getDouble("sellingPrice")});
                    total_price+=Login.rs.getDouble("sellingPrice");
                } else {
                    pdtMap.put(AddCodeTF.getText(), pdtMap.get(AddCodeTF.getText()) + 1);
                     int row_of_pdt=Arrays.asList(pdtMap.keySet().toArray()).indexOf(AddCodeTF.getText());
                    tm.setValueAt(pdtMap.get(AddCodeTF.getText()), row_of_pdt, 5);
                    tm.setValueAt(pdtMap.get(AddCodeTF.getText())*(double)tm.getValueAt(row_of_pdt, 6), row_of_pdt, 7);
                    total_price+=(double)tm.getValueAt(row_of_pdt, 6);
                 }
                 
                 //warning messages in case of running out of products
                 
                if(Login.rs.getInt("quantity")<5 && Login.rs.getInt("quantity")>1){
                    JOptionPane.showMessageDialog(null, "You are running out of this product");
                    
                }else if((Login.rs.getInt("quantity")==1)){
                    JOptionPane.showMessageDialog(null, "Last piece product");
                }else if((Login.rs.getInt("quantity")<=0)){
                    JOptionPane.showMessageDialog(null, "This product is unavailable,it will be stored with minus");
                }
                 
            }
            total_ammount+=1;
            AddCodeTF.setText("");
            AddCodeBtn.setEnabled(false);
            PNumTF.setText(String.valueOf(total_ammount));
            TotalTF.setText(String.valueOf(total_price));

            PrintBtn.setEnabled(true);
            NewOrderBtn.setEnabled(true);
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Database is not working\nplease contact Codotronic team", "Error", 0);
        }
    }//GEN-LAST:event_AddCodeBtnActionPerformed

    private void AddCodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCodeTFActionPerformed
        // TODO add your handling code here:
        AddCodeBtn.doClick();
    }//GEN-LAST:event_AddCodeTFActionPerformed

    private void NewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrderBtnActionPerformed
        
        Sell_Bill.billTab.insertTab("New Bill", null, new Sell_Bill_Panel(), null, Sell_Bill.billTab.getTabCount());
        NewOrderBtn.setEnabled(false);
        Sell_Bill.billTab.setSelectedIndex(Sell_Bill.billTab.getTabCount()-1);
        
    }//GEN-LAST:event_NewOrderBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AddCodeBtn;
    private javax.swing.JTextField AddCodeTF;
    private javax.swing.JTextField BillNumTF;
    private javax.swing.JTextField CashNameTF;
    private javax.swing.JTextField DateTF;
    public static javax.swing.JButton NewOrderBtn;
    private javax.swing.JTextField PNumTF;
    public javax.swing.JButton PrintBtn;
    private javax.swing.JTextField ShiftTF;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TimeTF;
    private javax.swing.JTextField TotalTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
  
}
